# Generated by Django 3.2.6 on 2021-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchIt',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=254)),
                ('direction', models.CharField(max_length=254)),
                ('created_on', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'cdr',
            },
        ),
    ]
